### ISSUE TITLE
Test geonode setup

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/helm-charts#5]
With the setup of geonode with cloud sql in https://github.com/SeaBee-no/seabee-geonode-charts/issues/3  we should start playing around with geonode to reveal problems with the setup. I can perhaps create a couple of users for @JamesSample, @deviirmr and @jemmima or we can use the admin user. Anyway, think we should check creating content on geonode like:
* Uploading layers
* editing styles
* integration with external clients like qgis, arcgis etc
* uploading documents

Feel free to suggest other things to break it, guess it shouldn't be too difficult to break it ;)

**Comment by JamesSample** [comment]
Some example scripts for adding data to GeoNode are [here](https://github.com/SeaBee-no/workflow_examples#seabee-workflow_examples).

Main priorities:

- Optimise resource allocation
- Backup and restore workflow (i.e. without corrupting PostGIS)
- Add datasets (image mosaics, vector data etc.)
- Expose images as WMSs
- Creating GeoNode "Maps" and editing styles
