### ISSUE TITLE
Bump geoserver version to 2.20.5

### ISSUE THREAD

**Issue by knl88** [SeaBee-no/helm-charts#9]
While solving https://github.com/SeaBee-no/seabee-geonode-charts/issues/7 I did not mange to update geoserver, due to some changes in the use of java between version 2.18 and 2.20. Not completely sure about the consequences, but we should try to bump after the seabee workshop at trysil. The problem lines are [here]( https://github.com/SeaBee-no/seabee-geonode-charts/blob/d0ace80c25d93a0e41084988989a9d2a2dcc9689/templates/geoserver-deploy.yaml#L88)

**Comment by JamesSample** [comment]
Is this still an issue, @knl88 ?

**Comment by knl88** [comment]
Fixed in https://github.com/SeaBee-no/helm-charts/commit/8f62e1d47694664bfcd4830339d5a3c17c1fb223
